export const curriculum = {
  mern: {
    modules: [
      {
        title: "Module 1",
        name: "HTML , CSS & Git",
        duration: "2 Weeks",
        description:
          "This module provides essential foundational skills in HTML, CSS, and Git, crucial for modern web development. Students will learn the fundamentals of structuring web pages with HTML5, styling them effectively using CSS3, and mastering version control with Git. Through hands-on projects and collaborative exercises, participants will gain proficiency in creating responsive and visually appealing web interfaces while adopting industry-standard practices for efficient code management and collaboration.",
        topics: [
          "How Web works ?",
          "Tags & Elements",
          "headings & paragraph",
          "Semantic tags",
          "Text formatting , img , a",
          "Forms",
          "Table",
          "iframes",
          "git & github",
          "inline, internal & external styling",
          "CSS Box Model",
          "block, inline-block & inline",
          "All basic CSS properties",
          "background",
          "Flex Layout",
          "Grid Layout",
          "Position & z-index",
          "transitions & transform",
          "Animations",
        ],
      },
      {
        title: "Module 2",
        name: "Javascript",
        duration: "4 weeks",
        description:
          "The JavaScript Core module is designed to equip students with a solid understanding of JavaScript, the cornerstone language of web development. Over the course of four weeks, participants will delve into fundamental concepts such as variables, data types, control structures, functions, and object-oriented programming principles. Practical sessions will focus on hands-on coding exercises and projects, enabling students to build a strong foundation in JavaScript for frontend and backend development within the MERN stack ecosystem. By the end of the module, students will be proficient in leveraging JavaScript to create dynamic and interactive web applications.",
        topics: [
          "Variables & Data types",
          "Operators",
          "Conditional statements",
          "Loops",
          "Hoisting",
          "Scope & Scope chain",
          "Higher order functions",
          "Strings, Arrays & Objects",
          "Asynchronous nature of javascript",
          "Event loop, Job Queue & Microtask queue",
          "Promises & Promise chaining",
          "OOPs",
        ],
      },
      {
        title: "Module 3",
        name: "Problem solving using javascript",
        duration: "6 weeks",
        description:
          "The Problem Solving Using JavaScript module is designed to enhance students' ability to tackle real-world challenges through systematic problem-solving techniques. Throughout this intensive three-week module, participants will learn to apply JavaScript effectively to analyze problems, devise algorithms, and implement solutions. Topics covered include data structures (arrays, linked lists, stacks, queues), algorithm design (recursion, sorting, searching), and strategies for optimizing code performance. Practical exercises and coding challenges will reinforce these concepts, empowering students to approach complex programming tasks with confidence and efficiency. By the end of the module, participants will have honed their problem-solving skills and be ready to tackle diverse programming challenges within the MERN stack environment.",
        topics: [
          "Complexity analysis",
          "Strings",
          "Arrays",
          "Stack & Queue",
          "LinkedList",
          "Tree ( binary & nary trees )",
          "DOM",
          "Browser storage elements",
          "fetch API",
        ],
      },
      {
        title: "Module 4",
        name: "React & Redux",
        duration: "6 weeks",
        description:
          "The React & Redux module immerses students in mastering two essential libraries for building modern, scalable web applications. Over the span of five weeks, participants will dive into React, learning to create dynamic user interfaces with components, state management, and lifecycle methods. They will then advance to Redux, exploring centralized state management through actions, reducers, and the Redux store. Practical projects and hands-on exercises will reinforce concepts such as routing, asynchronous actions, and integrating React with backend APIs. By the end of the module, students will be proficient in leveraging React and Redux to develop robust, responsive applications within the MERN stack ecosystem.",
        topics: [
          "React elements Vs DOM Elements",
          "VDOM, Diffing & Reconciliation",
          "Importance of keys in lists",
          "Components & Life cycle methods",
          "state & useState",
          "useEffect and it's usage",
          "useRef, useMemo, useCallback",
          "Context API",
          "Custom Hooks",
          "CSR Vs SSR",
          "React routing, lazy loading",
          "Need of global state management",
          "Redux architecture & terminology",
          "Middlewares",
          "Redux toolkit",
          "Shopping cart application",
        ],
      },
      {
        title: "Module 5",
        name: "Nodejs & MongoDB",
        duration: "6 weeks",
        description:
          "The Node.js & MongoDB module equips students with the skills necessary to build scalable backend solutions for web applications using Node.js and MongoDB. Over the course of four weeks, participants will delve into Node.js, learning to create server-side applications with asynchronous JavaScript, RESTful APIs, and middleware integration. They will also explore MongoDB, mastering document-based data modeling, CRUD operations, and aggregation pipelines. Practical projects will involve implementing authentication, data validation, and error handling strategies. By the end of the module, students will be adept at developing robust backend architectures that seamlessly integrate with frontend frameworks within the MERN stack.",
        topics: [
          "REST Methods",
          "REST APIs",
          "data sharing techniques",
          "Status Codes",
          "Middlewares",
          "Postman tool",
          "Templating Engines (ejs)",
          "Environment Variables",
          "Database connections",
          "CRUD Operations",
          "Mongoose & MongoDB",
          "Schema Design",
          "Express framework",
          "Authentication & Authorization",
          "JWT",
          "AWS App Runner",
          "Deployment",
        ],
      },
      {
        title: "Module 6",
        name: "Project Making & Resume building",
        duration: "4 weeks",
        description:
          "In this intensive four-week module, students will embark on a comprehensive journey to develop a fully functional bus booking platform using the MERN stack (MongoDB, Express.js, React, Node.js). Participants will start by conceptualizing the application's architecture and database schema using MongoDB for efficient data storage. They will then implement backend functionalities with Node.js and Express.js, including user authentication, booking management, and integration with third-party APIs for real-time data updates.",
        topics: [
          "Bus Booking platform",
          "Project planning & setup",
          "HLD & LLD",
          "Schema Design & Database modelling using MongoDB",
          "Backend environments setup ( dev & prod )",
          "Authentication & Authorization using JWT",
          "Scalable REST APIs building",
          "Frontend System Design",
          "Component architecture design ( HLD + LLD )",
          "Redux state design ( HLD + LLD )",
          "Setting up reusable components",
          "Adding the project in Resume",
        ],
      },
    ],
  },
  dsa: {
    modules: [
      {
        title: "Module 1",
        name: "Introduction to Java Programming",
        duration: "6 weeks",
        description: "",
        topics: [
          "Basics of Java programming language",
          "Variables, data types, operators, and expressions",
          "Control flow (if-else, switch-case, loops)",
          "Functions",
          "Primitive & Non primitive data types",
          "Packages",
          "Classes and objects",
          "Encapsulation, inheritance, and polymorphism",
          "Abstract classes and interfaces",
          "Method overriding and overloading",
          "Introduction to arrays and their manipulation",
          "String operations and methods",
          "Sorting arrays (bubble sort, insertion sort)",
          "Overview of Java Collections Framework",
          "ArrayList, LinkedList, HashSet, HashMap",
          "Iterators and ListIterators",
        ],
      },
      {
        title: "Module 2",
        name: "Linear Data Structures",
        duration: "6 weeks",
        description: "",
        topics: [
          "Complexity analysis",
          "Searching & Sorting",
          "Binary search",
          "Merge & Quick sort",
          "Arrays & it's methods",
          "Problems on Arrays",
          "Strings and it's methods",
          "Problems on Strings",
          "Sliding window technique",
          "Two pointer technique",
          "Stack data structure",
          "Problems on Stack",
          "Queue data structure",
          "Problems on Queue",
          "Linkedlist",
          "Problems on Linked List",
          "Doubly linked list & circualar linked list",
        ],
      },
      {
        title: "Module 3",
        duration: "4 weeks",
        name: "Hierarchical Data Structure",
        topics: [
          "Recursion & Recursion tree",
          "Tree data structure",
          "Tree traversals ( DFS , BFS )",
          "Problems on binary trees",
          "Binary Search Tree (BST)",
          "AVL Tree",
          "n`ary Trees",
          "Trie data structure",
          "Graph representation",
          "Graph traversals (DFS, BFS)",
          "Connected components",
          "Cycle detection in a graph",
          "Shortest path between two nodes",
          "Minimum Spanning Tree (MST)",
          "Grid dfs & bfs",
        ],
      },
      {
        title: "Module 4",
        name: "Advanced Algorithms",
        duration: "2 weeks",
        topics: [
          "Segment trees",
          "Divide & Conquer technique",
          "Dynamic Programming ( Recursive & Iterative )",
          "Bit Manipulation",
        ],
      },
    ],
  },
};
